language: c
services:
  - riak
before_install:
  - sudo pip install cpp-coveralls
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check protobuf-c-compiler libprotobuf-c0-dev
before_script:
  - autoreconf -i
script:
  - ./configure --enable-silent-rules CFLAGS="-Wall -Wextra -O0 -g -pg  -fprofile-arcs -ftest-coverage" LDFLAGS="-pg"
  - make
  - make check
compiler:
  - gcc
  - clang
